### ISSUE TITLE
Running with METEOR

### ISSUE THREAD

**Issue by antonisa** [pmichel31415/teapot-nlp#2]
Hi,
attempting to run with METEOR (python 3.7, on mac) I encounter the following issue that is related to the argparser:

If specifying --meteor-jar and *only* --s-src it works.
If specifying --meteor-jar and *only* --s-tgt it works.
If specifying --meteor-jar and *both* --s-src --s-tgt the argparser returns an error:

> argparse.ArgumentError: argument --meteor-jar: conflicting option string: --meteor-jar

The solution to this is to change line 8 of main.py from
`parser = argparse.ArgumentParser("")`
to
`parser = argparse.ArgumentParser(conflict_handler="resolve")`

**Comment by pmichel31415** [comment]
Thanks for flagging this, I have just pushed a fix to github (and pypi). Feel free to reopen if the issue persists
